import type { Metadata } from 'next'
import { Noto_Sans, Sora } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'

const sora = Sora({
  variable: '--font-sora',
  subsets: ['latin'],
  display: 'swap',
})

const notoSans = Noto_Sans({
  variable: '--font-noto-sans',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${sora.variable} ${notoSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
